version: "3.8"

services:
  server-go:
    build: .
    ports:
      - "8087:8080"
    container_name: url-shortener-server-go
    depends_on:
      db:
        condition: service_healthy
    restart: always
  db:
    image: postgres
    restart: always
    container_name: url-shortener-postgres-db
    shm_size: 128mb
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: 'url_shortener'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5