env: "local"
storage_path: "./storage/storage.db"

http_server:
  address: "0.0.0.0:8080"
  timeout: 4s
  idle_timeout: 60s
  user: Roman
  password: RomanPass

postgres:
  host: url-shortener-postgres-db
  user: root
  password: root
  dbname: url_shortener